version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/Dockerfile-dev
    command: /start-dev.sh
    environment:
      - PORT={PORT}
      - NODE_ENV=development
    ports:
      - '80:3000'
    expose:
      - '80'
    networks:
      - default-network
    volumes:
      - ./:/home/service/test/frontend/
      - node_modules:/home/service/test/frontend/node_modules/

volumes:
  node_modules:

networks:
  default-network:
    driver: bridge